[appsettings]
DAY="SATURDAY"
NTH=2

[credentials]
HOST=""
PORT=587
SECURITY="STARTTLS"
USER=""
PASSWORD_ENV_NAME=""
SEND_FROM=""

[emailsettings]
SEND_TO=[
]
MESSAGE="""
Hello from veckarklocka,
Everything seems to be working now!
"""
SUBJECT="Testing veckarklocka"